# Generated by Django 2.2.2 on 2021-06-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails_body',
            name='file',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
